# Generated by Django 4.2.7 on 2023-11-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image_url', models.URLField(default='')),
            ],
        ),
    ]
